deploy:
  rsync:
    user: root
    host: staging.properdesign.rs
    port: 22
    source: .
    target: /www
    delete: true
    when:
      branch: develop
    recursive: true
    exclude:
      - .git/
      - .gitignore
      - .drone.yml
      - plugins
      - uploads
    commands:
      # - cd /www/newmet
      # - proper-site-install
notify:
  slack:
    webhook_url: https://hooks.slack.com/services/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
    channel: build
    username: drone
    when:
      success: false
      failure: true
      change: true