deploy:
  rsync:
    user: drone
    host: staging.properdesign.rs
    port: 22
    source: .
    target: /www
    delete: false
    when:
      branch: develop
    recursive: true
    exclude:
      - ".git/"
      - ".gitignore"
      - ".drone.yml"
    commands:
      # - 
notify:
  slack:
    webhook_url: https://hooks.slack.com/services/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
    channel: build
    username: drone
    when:
      success: false
      failure: true
      change: true