build:
  lint-bum:
    image: ubuntu
    commands:
      - $(! grep --exclude-dir=node_modules --include=\*.php -rlnw '.' -e 'bum')
      - $(! grep --exclude-dir=node_modules --include=\*.js -rlnw '.' -e "bum")
  frontend:
    image: properdesign/proper-build
    pull: true
    commands:
      - DRONE_ROOT=$(pwd)
      - cp -r * /source
      - cd /build
      - gulp sass
      - gulp scripts
      - gulp svg
      - cp -r /source/* $DRONE_ROOT
deploy:
  rsync:
    user: root
    host: staging.properdesign.rs
    port: 22
    source: .
    target: /www
    delete: true
    when:
      branch: develop
    recursive: true
    exclude:
      - .git/
      - .gitignore
      - .drone.yml
      - plugins
      - uploads
    commands:
      # - 
notify:
  slack:
    webhook_url: https://hooks.slack.com/services/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
    channel: build
    username: drone
    when:
      success: false
      failure: true
      change: true