deploy:
  rsync:
    user: root
    host: properdesign.rs
    port: 22
    source: /drone/src/bitbucket.org/proper-design/properdesign/themes/properdesign/*
    target: /var/www/properdesign.rs/web/wp-content/themes/properdesign/
    delete: true
    when:
      branch: master
    recursive: true
    exclude:
      - .git/
      - .gitignore
      - .drone.yml
      - plugins
      - uploads
    commands:
      # - 
notify:
  slack:
    webhook_url: https://hooks.slack.com/services/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
    channel: build
    username: drone
    when:
      success: false
      failure: true
      change: true