wordpress:
  build: ./
  restart: always
  container_name: ${PROPERDOCKER_NAME}
  external_links:
    - ${PROPERDOCKER_DB}:mysql
  environment:
    # tell HTTPS-PORTAL to set up "example.com"
    VIRTUAL_HOST: ${PROPERDOCKER_URL}
    WORDPRESS_DEBUG: ${PROPERDOCKER_DEBUG}
    WORDPRESS_DB_NAME: ${PROPERDOCKER_NAME}
    PROPERDOCKER_NAME: ${PROPERDOCKER_NAME}
    PROPERDOCKER_URL: ${PROPERDOCKER_URL}
    PROPERDOCKER_DB: ${PROPERDOCKER_DB}
    PROPERDOCKER_ADMIN_USER: ${PROPERDOCKER_ADMIN_USER}
    PROPERDOCKER_ADMIN_PASSWORD: ${PROPERDOCKER_ADMIN_PASSWORD}
    PROPERDOCKER_ADMIN_EMAIL: ${PROPERDOCKER_ADMIN_EMAIL}
    PROPERDOCKER_MIGRATEDB_URL: ${PROPERDOCKER_MIGRATEDB_URL}
    PROPERDOCKER_MIGRATEDB_KEY: ${PROPERDOCKER_MIGRATEDB_KEY}
    PROPERDOCKER_STAGE: ${PROPERDOCKER_STAGE}
    WPMDBP_LICENCE: ${WPMDBP_LICENCE}
    ACF_LICENCE: ${ACF_LICENCE}
  volumes:
    - ${PWD}/uploads:/var/www/html/wp-content/uploads
    - ${PWD}/plugins:/var/www/html/wp-content/plugins
    - ${PWD}/themes:/var/www/html/wp-content/themes
  log_driver: "json-file"
  log_opt:
      max-size: "10m"
      max-file: "10"