wordpress:
  build: ./
  restart: ${PROPERDOCKER_RESTART}
  container_name: ${PROPERDOCKER_NAME}
  external_links:
    - ${PROPERDOCKER_DB}:mysql
  environment:
    # tell HTTPS-PORTAL to set up "example.com"
    VIRTUAL_HOST: ${PROPERDOCKER_URL}
    WORDPRESS_DEBUG: ${PROPERDOCKER_DEBUG}
    PROPERDOCKER_NAME: ${PROPERDOCKER_NAME}
  volumes:
    - ${PWD}/uploads:/var/www/html/wp-content/uploads
    - ${PWD}/plugins:/var/www/html/wp-content/plugins
    - ${PWD}/themes:/var/www/html/wp-content/themes